<!DOCTYPE html>
<html>
<head>
<title>Update ID Request</title>
<link rel="stylesheet" type="text/css" href="css/bootstrap.css"/>
	<link rel="stylesheet" type="text/css" href="mystyle.css"/>
	<link rel="stylesheet" type="text/css" href="css/fonts.css"/>
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>

</head>
<body>
<div class="container">
    <div class="col-sm-6">
    <?php
    $postfix="";
    $prefix="";
    $id_generated="";

$conn=new mysqli("localhost","root","","webproject_db");
 $id=$_GET['id'];
 $select="SELECT * FROM id_request_tbl WHERE id='$id'";
 $run= $conn->query($select);
 if($run->num_rows>0){
     while ($row= $run->fetch_array()) {
         $user_email=$row['user_email'];
         $user_province=$row['user_province'];
   }
   switch ($user_province) {
       case 'punjab';
           $prefix="pun";
           $rand=rand(9999999,1234567);
           $postfix="xyz";
           $id_generated="$prefix$rand$postfix";
           break;
       case 'sindh';
       $prefix="sin";
       $rand=rand(9999999,1234567);
       $postfix="xyz";
       $id_generated="$prefix$rand$postfix";
       break;
       case 'kpk';
       $prefix="kpk";
       $rand=rand(9999999,1234567);
       $postfix="xyz";
       $id_generated="$prefix$rand$postfix";
       break;
       case 'balochistan';
       $prefix="baloch";
       $rand=rand(9999999,1234567);
       $postfix="xyz";
       $id_generated="$prefix$rand$postfix";
       break;
       default:
           break;
   }    
         ?>

<form method="POST">
<div class="form-group">
        <label for="exampleInputEmail">User Email</label>
        <input type="email" name="user_email" class="form-control" id="exampleInputEmail" placeholder="Enter Email"
        required readonly value="<?php echo $user_email;?>">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail">User Province</label>
        <input type="text" name="user_province" class="form-control" id="exampleInputEmail" placeholder="Enter province"
        required readonly value="<?php echo $user_province;?>">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail">User ID generated by System</label>
        <input type="text" name="user_id_generated" class="form-control" id="exampleInputEmail" placeholder="Enter province"
        required readonly value="<?php echo strtoupper($id_generated);?>">
        <br>
        <div class="form-group">
        <input type="submit" name="update" value="Update user ID" class="form-group btn btn-success">
        </div>
    </div>
 </form> 
<?php
 }
 else {
     echo "Record not found";
 }
?>
</div>
    <div class="col-sm-6">
</div>    

</div>
</body>
</html>

<?php
if(isset($_POST['update'])){
$user_email=$_POST['user_email'];
$user_id_generated=$_POST['user_id_generated'];
$update="update user_db set user_id_generated ='$user_id_generated'where user_email='$user_email'";
$run=$conn->query($update);
if ($run) {
    echo "<script>alert('Update Succesfully!')</script>";
    $delete="DELETE from id_request_tbl where user_email='$user_email'";
    $del=$conn->query($delete);
    if ($del) {
        echo "<script> alert('Update Successfully and Deleted') </script>";
        echo "<script> window.location.href='idrequest.php' </script>";
    }
}
else {
    echo "<script>alert('Something Went wrong! Error')</script>";
}
}
?>